["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "/Users/clementwalter/.pyenv/versions/3.9.13/envs/starksheet/lib/python3.9/site-packages/"

["protostar.contracts"]
Sheet = ["contracts/sheet/Sheet.cairo"]
Starksheet = ["contracts/starksheet/Starksheet.cairo"]
BasicCellRenderer = ["contracts/renderers/BasicCellRenderer.cairo"]
math = ["contracts/utils/math.cairo"]
