/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface EvmsheetScriptInterface extends utils.Interface {
  functions: {
    "IS_SCRIPT()": FunctionFragment;
    "evmsheet()": FunctionFragment;
    "math()": FunctionFragment;
    "multicall()": FunctionFragment;
    "renderer()": FunctionFragment;
    "run()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "IS_SCRIPT"
      | "evmsheet"
      | "math"
      | "multicall"
      | "renderer"
      | "run",
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "IS_SCRIPT", values?: undefined): string;
  encodeFunctionData(functionFragment: "evmsheet", values?: undefined): string;
  encodeFunctionData(functionFragment: "math", values?: undefined): string;
  encodeFunctionData(functionFragment: "multicall", values?: undefined): string;
  encodeFunctionData(functionFragment: "renderer", values?: undefined): string;
  encodeFunctionData(functionFragment: "run", values?: undefined): string;

  decodeFunctionResult(functionFragment: "IS_SCRIPT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "evmsheet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "math", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renderer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "run", data: BytesLike): Result;

  events: {};
}

export interface EvmsheetScript extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EvmsheetScriptInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<[boolean]>;

    evmsheet(overrides?: CallOverrides): Promise<[string]>;

    math(overrides?: CallOverrides): Promise<[string]>;

    multicall(overrides?: CallOverrides): Promise<[string]>;

    renderer(overrides?: CallOverrides): Promise<[string]>;

    run(
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;
  };

  IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

  evmsheet(overrides?: CallOverrides): Promise<string>;

  math(overrides?: CallOverrides): Promise<string>;

  multicall(overrides?: CallOverrides): Promise<string>;

  renderer(overrides?: CallOverrides): Promise<string>;

  run(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  callStatic: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

    evmsheet(overrides?: CallOverrides): Promise<string>;

    math(overrides?: CallOverrides): Promise<string>;

    multicall(overrides?: CallOverrides): Promise<string>;

    renderer(overrides?: CallOverrides): Promise<string>;

    run(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<BigNumber>;

    evmsheet(overrides?: CallOverrides): Promise<BigNumber>;

    math(overrides?: CallOverrides): Promise<BigNumber>;

    multicall(overrides?: CallOverrides): Promise<BigNumber>;

    renderer(overrides?: CallOverrides): Promise<BigNumber>;

    run(overrides?: Overrides & { from?: string }): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    evmsheet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    math(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    multicall(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renderer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    run(
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;
  };
}
