[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
eth_rpc_url = "anvil"

[profile.docker]
eth_rpc_url = "docker"

[profile.linea]
eth_rpc_url = "linea"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
linea = "https://linea-mainnet.infura.io/v3/${INFURA_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
polygon-mainnet = "https://polygon-mainnet.infura.io/v3/${INFURA_KEY}"
polygon-mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_KEY}"
optimism-mainnet = "https://optimism-mainnet.infura.io/v3/${INFURA_KEY}"
optimism-goerli = "https://optimism-goerli.infura.io/v3/${INFURA_KEY}"
arbitrum-mainnet = "https://arbitrum-mainnet.infura.io/v3/${INFURA_KEY}"
arbitrum-goerli = "https://arbitrum-goerli.infura.io/v3/${INFURA_KEY}"
palm-mainnet = "https://palm-mainnet.infura.io/v3/${INFURA_KEY}"
palm-goerli = "https://palm-goerli.infura.io/v3/${INFURA_KEY}"
avalanche-mainnet = "https://avalanche-mainnet.infura.io/v3/${INFURA_KEY}"
avalanche-fuji = "https://avalanche-fuji.infura.io/v3/${INFURA_KEY}"
aurora-mainnet = "https://aurora-mainnet.infura.io/v3/${INFURA_KEY}"
aurora-testnet = "https://aurora-testnet.infura.io/v3/${INFURA_KEY}"
celo-mainnet = "https://celo-mainnet.infura.io/v3/${INFURA_KEY}"
celo-alfajores = "https://celo-alfajores.infura.io/v3/${INFURA_KEY}"
manta = "https://pacific-rpc.manta.network/http"

anvil = "http://127.0.0.1:8545"
kakarot = "http://127.0.0.1:3030"
docker = "${RPC_URL}"

[etherscan]
goerli = { key = "${GOERLI_EXPLORER_KEY}" }
linea = { key = "${LINEA_EXPLORER_KEY}" }
