name: Deploy

on:
  push:
    branches:
      - staging

jobs:
  merge-testnet:
    name: Merge Staging to Testnet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Staging to Testnet
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout testnet
          git merge staging --no-edit
          git push

  merge-testnet2:
    name: Merge Staging to Testnet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Staging to Testnet
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout testnet2
          git merge staging --no-edit
          git push

  merge-goerli:
    name: Merge Staging to Goerli
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Staging to Goerli
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout goerli
          git merge staging --no-edit
          git push
