name: Deploy staging

permissions: read-all

on:
  push:
    branches:
      - staging

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        branch: [testnet, testnet2, goerli]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin ${{ matrix.branch }}
          git checkout ${{ matrix.branch }}
          git reset staging --hard
          git push origin ${{ matrix.branch }} -f
